name             'omnibus_updater_windows'
maintainer       'Biola University'
maintainer_email 'jared.king@biola.edu'
license          'Apache 2.0'
description      'Upgrades chef-client on Windows systems'
long_description 'Upgrades chef-client on Windows systems'
source_url       'https://github.com/biola/chef-omnibus_updater_windows'
issues_url       'https://github.com/biola/chef-omnibus_updater_windows/issues'
version          '1.0.4'
